[default.databases.sqlx]
url = "postgres://etu_attend_app:12346543@localhost"

[default.tls]
key = "tls/key.pem"
certs = "tls/cert.pem"

[global.cors]
enable = true

[default]
port=5443

[prod]
address="0.0.0.0"
port=443
