[default.databases.sqlx]
url = "postgres://etu_attend_app:12346543@localhost"

max_connections = 50
#connect_timeout = 5
#idle_timeout = 120

[default.tls]
key = "tls/key.pem"
certs = "tls/cert.pem"

[global.cors]
enable = true

[default]
port=5443
log_level="normal"

[production]
address="0.0.0.0"
port=443
log_level="critical"
